
services:
  app:
    build: .
    container_name: imagebot_app
    working_dir: /usr/src/app
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - .:/usr/src/app
    command: npm run start
    